name: Node.js CI

on:
  push:
    branches: [ "main" , "develop" ]
  pull_request:
    branches: [ "main" , "develop"]

jobs:
  buildAPI:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: api/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

  buildClient:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
